IDLE_MOVE_REWARD = -10
VALID_MOVE_REWARD = 0
INVALID_MOVE_REWARD = -5

VALID_PUZZLE_REWARD = 8
INVALID_PUZZLE_REWARD = -5
SOLVED_PUZZLE_REWARD = -10  # Trying to complete a completed puzzle

COMPLETED_PUZZLE_REWARD = 10

# Heuristics
INVALID_ACTION_TAKEN_DISCOUNT = 0.0001
