IDLE_MOVE_REWARD = -20
VALID_MOVE_REWARD = -0.01
INVALID_MOVE_REWARD = -10

VALID_PUZZLE_REWARD = 10
INVALID_PUZZLE_REWARD = -0.015
COMPLETED_PUZZLE_REWARD = -1  # Trying to complete a completed puzzle

TERMINAL_PUZZLE_REWARD = 100
